// Code generated by "marker -output track_marker_generated.go -method IsOpType -type FixedTrack,MetaTrack"; DO NOT EDIT.

package midix

func (*FixedTrack) IsOpType() {}
func (*MetaTrack) IsOpType()  {}
