// Code generated by "stringer -type DegreeName -output degree_stringer_generated.go"; DO NOT EDIT.

package note

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownDegree-0]
	_ = x[MajorDegree-1]
	_ = x[MinorDegree-2]
	_ = x[PerfectDegree-3]
	_ = x[AugmentedDegree-4]
	_ = x[DiminishedDegree-5]
	_ = x[DoublyAugmentedDegree-6]
	_ = x[DoublyDiminishedDegree-7]
}

const _DegreeName_name = "UnknownDegreeMajorDegreeMinorDegreePerfectDegreeAugmentedDegreeDiminishedDegreeDoublyAugmentedDegreeDoublyDiminishedDegree"

var _DegreeName_index = [...]uint8{0, 13, 24, 35, 48, 63, 79, 100, 122}

func (i DegreeName) String() string {
	if i < 0 || i >= DegreeName(len(_DegreeName_index)-1) {
		return "DegreeName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DegreeName_name[_DegreeName_index[i]:_DegreeName_index[i+1]]
}
