// Code generated by "stringer -type Name -output name_stringer_generated.go"; DO NOT EDIT.

package note

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[C-0]
	_ = x[D-1]
	_ = x[E-2]
	_ = x[F-3]
	_ = x[G-4]
	_ = x[A-5]
	_ = x[B-6]
}

const _Name_name = "CDEFGAB"

var _Name_index = [...]uint8{0, 1, 2, 3, 4, 5, 6, 7}

func (i Name) String() string {
	if i < 0 || i >= Name(len(_Name_index)-1) {
		return "Name(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Name_name[_Name_index[i]:_Name_index[i+1]]
}
