// Code generated by "stringer -type Chord -output chord_stringer_generated.go"; DO NOT EDIT.

package chord

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MajorTriad-0]
	_ = x[MinorTriad-1]
	_ = x[DiminishedTriad-2]
	_ = x[AugmentedTriad-3]
	_ = x[DominantSeventh-4]
	_ = x[MajorSeventh-5]
	_ = x[MinorSeventh-6]
	_ = x[MinorMajorSeventh-7]
	_ = x[DiminishedSeventh-8]
	_ = x[HalfDiminishedSeventh-9]
	_ = x[AugmentedSeventh-10]
	_ = x[AugmentedMajorSeventh-11]
	_ = x[AddSixth-12]
	_ = x[MinorAddSixth-13]
	_ = x[SuspendedForth-14]
	_ = x[AddNinth-15]
	_ = x[MinorAddNinth-16]
}

const _Chord_name = "MajorTriadMinorTriadDiminishedTriadAugmentedTriadDominantSeventhMajorSeventhMinorSeventhMinorMajorSeventhDiminishedSeventhHalfDiminishedSeventhAugmentedSeventhAugmentedMajorSeventhAddSixthMinorAddSixthSuspendedForthAddNinthMinorAddNinth"

var _Chord_index = [...]uint8{0, 10, 20, 35, 49, 64, 76, 88, 105, 122, 143, 159, 180, 188, 201, 215, 223, 236}

func (i Chord) String() string {
	if i < 0 || i >= Chord(len(_Chord_index)-1) {
		return "Chord(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Chord_name[_Chord_index[i]:_Chord_index[i+1]]
}
