// Code generated by "stringer -type KeyConversion -output circle_stringer_generated.go"; DO NOT EDIT.

package op

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownKeyConversion-0]
	_ = x[ParallelKey-1]
	_ = x[RelativeKey-2]
	_ = x[DominantKey-3]
	_ = x[SubDominantKey-4]
}

const _KeyConversion_name = "UnknownKeyConversionParallelKeyRelativeKeyDominantKeySubDominantKey"

var _KeyConversion_index = [...]uint8{0, 20, 31, 42, 53, 67}

func (i KeyConversion) String() string {
	if i < 0 || i >= KeyConversion(len(_KeyConversion_index)-1) {
		return "KeyConversion(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _KeyConversion_name[_KeyConversion_index[i]:_KeyConversion_index[i+1]]
}
