// Code generated by "marker -method IsNode -type Transposition,Instrument,Key,Tempo,Meter,Rest,Chord -output ast_marker_generated.go"; DO NOT EDIT.

package ast

func (*Transposition) IsNode() {}
func (*Instrument) IsNode()    {}
func (*Key) IsNode()           {}
func (*Tempo) IsNode()         {}
func (*Meter) IsNode()         {}
func (*Rest) IsNode()          {}
func (*Chord) IsNode()         {}
