// Code generated by "marker -output chords_marker_generated.go -method IsNode -type ChordList,Chord,ChordDegree,ChordSymbol,ChordBase,ChordValues,ChordValue,Rest"; DO NOT EDIT.

package ast

func (*ChordList) IsNode()   {}
func (*Chord) IsNode()       {}
func (*ChordDegree) IsNode() {}
func (*ChordSymbol) IsNode() {}
func (*ChordBase) IsNode()   {}
func (*ChordValues) IsNode() {}
func (*ChordValue) IsNode()  {}
func (*Rest) IsNode()        {}
